spring:
  # 对应 RedisProperties 类
  redis:
    database: 0  # Redis数据库索引，Redis默认情况下有16个，默认是0
    host:  172.0.0.1 # Redis服务器地址
    port:  6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 10000 # 客户端超时时间单位是毫秒 默认是2000
    jedis: # 或lettuce
      pool:
        max-active: 8 # 连接池的最大数据库连接数。设为0表示无限制
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间(使用负值表示没有限制)默认-1
    cluster: # 普通集群，不使用则不用开启
      max-redirects: 3 # 在群集中执行命令时遵循的最大重定向数
      # 以逗号分隔的“主机：端口”对列表进行引导。
      nodes: 127.0.0.1:8061,127.0.0.1:8062,127.0.0.1:8063,127.0.0.1:8064,127.0.0.1:8065,127.0.0.1:8066